// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj7vwurdjJbYoFAeY7te3TCK2XwBo7rz4',
    appId: '1:627920301535:web:c315127e63a5bde10c686a',
    messagingSenderId: '627920301535',
    projectId: 'flutter-task-manager-f3db9',
    authDomain: 'flutter-task-manager-f3db9.firebaseapp.com',
    storageBucket: 'flutter-task-manager-f3db9.firebasestorage.app',
    measurementId: 'G-W9TJ35QNVB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5J_JPD_0noZ4kPt21x-iXLaD-GVHErzM',
    appId: '1:627920301535:android:b42051023e83d3410c686a',
    messagingSenderId: '627920301535',
    projectId: 'flutter-task-manager-f3db9',
    storageBucket: 'flutter-task-manager-f3db9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU7b529HCmOhBXSzftvl48DmQXPaPi71c',
    appId: '1:627920301535:ios:87465fc01640e80e0c686a',
    messagingSenderId: '627920301535',
    projectId: 'flutter-task-manager-f3db9',
    storageBucket: 'flutter-task-manager-f3db9.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseTaskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU7b529HCmOhBXSzftvl48DmQXPaPi71c',
    appId: '1:627920301535:ios:87465fc01640e80e0c686a',
    messagingSenderId: '627920301535',
    projectId: 'flutter-task-manager-f3db9',
    storageBucket: 'flutter-task-manager-f3db9.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseTaskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDj7vwurdjJbYoFAeY7te3TCK2XwBo7rz4',
    appId: '1:627920301535:web:015bad78ab729c940c686a',
    messagingSenderId: '627920301535',
    projectId: 'flutter-task-manager-f3db9',
    authDomain: 'flutter-task-manager-f3db9.firebaseapp.com',
    storageBucket: 'flutter-task-manager-f3db9.firebasestorage.app',
    measurementId: 'G-7090KXGC9Q',
  );
}
